global:
  image:
    registry: registry.k8s.io

controller:
  hostNetwork: true
  image:
    image: ingress-nginx/controller
    tag: "v1.13.4"
  containerPort:
    http: 80
    https: 443
    grpc: 4137
  service:
    type: LoadBalancer
    loadBalancerIP: ${INGRESS_LOADBALANCER_IP}
  admissionWebHooks:
    patch:
      enabled: true
      image:
        image: ingress-nginx/kube-webhook-certgen
        tag: v1.6.4
  nodeSelector:
    node-role.kubernetes.io/worker: ""

defaultBackend:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
