controller:
  hostNetwork: true
  containerPort:
    http: 80
    https: 443
    gprc: 4137
  service:
    type: LoadBalancer
    loadBalancerIP: ${INGRESS_LOADBALANCER_IP}
  nodeSelector:
    node-role.kubernetes.io/worker: ""

defaultBackend:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
