{
 "title": "Trino Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "trino_execution_name_QueryExecution_Executor_TaskCount"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Coordinators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(trino_metadata_name_DiscoveryNodeManager_ActiveNodeCount{namespace=\"$namespace\", job=~\".*coordinator.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(trino_metadata_name_DiscoveryNodeManager_ActiveNodeCount{namespace=\"$namespace\", job=~\".*worker.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Inactive Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)  (trino_metadata_name_DiscoveryNodeManager_InactiveNodeCount{namespace=\"$namespace\", job=~\".*coordinator.*\"})"
    }
   ]
  },
  {
   "title": "Active Hive Metastores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas_available{namespace=\"$namespace\", instance=\"kube-state-metrics.kube-system.svc:8080\", deployment=~\".*hive.*\" }==1) or vector(0)"
    }
   ]
  },
  {
   "title": "Bytes Spilled to Disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(trino_spiller_name_SpillerStats_TotalSpilledBytes{namespace=\"$namespace\"} [2m])"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 20, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Available Processors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (trino_memory_name_ClusterMemoryManager_TotalAvailableProcessors{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum by (namespace) (trino_memory_type_ClusterMemoryPool_name_general_FreeDistributedBytes{namespace=\"$namespace\", job=~\".*coordinator.*\"}) / (sum by (namespace) (trino_memory_type_ClusterMemoryPool_name_general_TotalDistributedBytes{namespace=\"$namespace\", job=~\".*coordinator.*\"})))"
    }
   ]
  },
  {
   "title": "Core Pool Utilization (CPU)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-((sum by (namespace) (trino_execution_name_QueryExecution_Executor_CorePoolSize{namespace=\"$namespace\", job=~\".*coordinator.*\"}) - sum by (namespace) (trino_execution_name_QueryExecution_Executor_PoolSize{namespace=\"$namespace\", job=~\".*coordinator.*\"})) / (sum by (namespace) (trino_execution_name_QueryExecution_Executor_CorePoolSize{namespace=\"$namespace\", job=~\".*coordinator.*\"})))"
    }
   ]
  },
  {
   "title": "Cache Requests per Minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_type_name_TypeOperatorsCache_CacheRequestCount{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_FailedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum by (namespace) (trino_memory_type_ClusterMemoryPool_name_general_FreeDistributedBytes{namespace=\"$namespace\", job=~\".*coordinator.*\"}) / (sum by (namespace) (trino_memory_type_ClusterMemoryPool_name_general_TotalDistributedBytes{namespace=\"$namespace\", job=~\".*coordinator.*\"})))"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (trino_type_name_TypeOperatorsCache_CacheHitRate{namespace=\"$namespace\", job=~\".*coordinator.*\"})"
    }
   ]
  },
  {
   "title": "SLA Execution Time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, quantile) (trino_execution_name_QueryManager_ExecutionTime_AllTime{namespace=\"$namespace\"})",
     "legendFormat": " {{ quantile }} Percentile"
    }
   ]
  },
  {
   "title": "Leaked Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (floor(increase(trino_memory_name_ClusterMemoryManager_NumberOfLeakedQueries{namespace=\"$namespace\"} [2m])))"
    }
   ]
  },
  {
   "title": "OOM Killed Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (floor(increase(trino_memory_name_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{namespace=\"$namespace\"} [2m])))"
    }
   ]
  },
  {
   "title": "OOM Killed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (floor(increase(trino_memory_name_ClusterMemoryManager_TasksKilledDueToOutOfMemory{namespace=\"$namespace\"} [2m])))"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (trino_type_name_TypeOperatorsCache_CacheMissRate{namespace=\"$namespace\", job=~\".*coordinator.*\"})"
    }
   ]
  },
  { "title": "Coordinator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Submitted Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_SubmittedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Started Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_StartedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_RunningQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Completed Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_CompletedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Queued Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_QueuedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_FailedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Abandoned Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_AbandonedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Expired Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_QueryTracker_ExpiredQueriesCount{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pruned Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_QueryTracker_PrunedQueriesCount{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Canceled Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_CanceledQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "All Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_CompletedQueries{namespace=\"$namespace\", job=~\".*coordinator.*\"} [5m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Consumed Input Rows",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_execution_name_QueryManager_ConsumedInputRows{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Input Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_execution_name_QueryManager_CpuInputByteRate_AllTime_Total{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Wall Input Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_execution_name_QueryManager_WallInputBytesRate_AllTime_Total{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Consumed CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_execution_name_QueryManager_ConsumedCpuTimeSecs{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Consumed Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_execution_name_QueryManager_ConsumedInputBytes{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_execution_name_QueryManager_ExecutionTime_AllTime_sum{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Queued Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(trino_execution_name_QueryManager_QueuedTime_AllTime_sum{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "External Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_ExternalFailures{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Internal Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_InternalFailures{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Active Executors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by (namespace) (trino_execution_name_QueryExecution_Executor_ActiveCount{namespace=\"$namespace\", job=~\".*coordinator.*\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Shutdown Executors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 57 },
   "targets": [
    {
     "expr": "sum by (namespace) (trino_execution_name_QueryExecution_Executor_Shutdown{namespace=\"$namespace\", job=~\".*coordinator.*\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Insufficient Resource Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_InsufficientResourcesFailures{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "User Error Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "targets": [
    {
     "expr": "floor(sum by (namespace) (increase(trino_execution_name_QueryManager_UserErrorFailures{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Terminated Executors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (namespace) (trino_execution_name_QueryExecution_Executor_Terminated{namespace=\"$namespace\", job=~\".*coordinator.*\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Completed Task Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(trino_execution_name_QueryExecution_Executor_CompletedTaskCount{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Queued Task Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(trino_execution_name_QueryExecution_Executor_QueuedTaskCount{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Task Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(trino_execution_name_QueryExecution_Executor_TaskCount{namespace=\"$namespace\", job=~\".*coordinator.*\"} [2m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Worker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Created Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "floor(increase(trino_execution_name_SqlTaskManager_CreatedTasks{namespace=\"$namespace\", job=~\".*worker.*\"} [2m]))"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "targets": [
    {
     "expr": "floor(increase(trino_execution_name_SqlTaskManager_FailedTasks{namespace=\"$namespace\", job=~\".*worker.*\"} [2m]))"
    }
   ]
  },
  {
   "title": "Tracked Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "floor(increase(trino_execution_name_SqlTaskManager_TrackedTasksCount{namespace=\"$namespace\", job=~\".*worker.*\"} [2m]))"
    }
   ]
  },
  {
   "title": "Input Data Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(trino_execution_name_SqlTaskManager_InputDataSize{namespace=\"$namespace\", job=~\".*worker.*\"} [2m])"
    }
   ]
  },
  {
   "title": "Output Data Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(trino_execution_name_SqlTaskManager_OutputDataSize{namespace=\"$namespace\", job=~\".*worker.*\"} [2m])"
    }
   ]
  }
 ]
}