---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pgsql-pvc.yaml
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: pgsql-secret
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: postgresdb
      app.kubernetes.io/name: postgresdb
      app.kubernetes.io/part-of: grafana-kube-stack
      kustomize.component: postgres
