---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - prometheus-ingress.yaml

configMapGenerator:
  - name: prometheus-nginx-params
    envs:
      - params.env

secretGenerator:
  - name: prometheus-auth
    files:
      - auth
  - name: prometheus-tls
    behavior: create
    type: "kubernetes.io/tls"
    files:
      - tls.crt=prometheus.crt
      - tls.key=prometheus.key

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      fieldPath: data.PROMETHEUS_DOMAINNAME
      kind: ConfigMap
      name: prometheus-nginx-params
      version: v1
    targets:
      - select:
          name: prometheus-ingress
          kind: Ingress
        fieldPaths:
          - spec.tls.*.hosts.0
          - spec.rules.0.host
  - source:
      fieldPath: data.namespace
      kind: ConfigMap
      name: prometheus-nginx-params
      version: v1
    targets:
      - select:
          name: prometheus-ingress
          kind: ingress
        fieldPaths:
          - metadata.namespace


labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: prometheus-ingress
      app.kubernetes.io/name: nginx
      app.kubernetes.io/part-of: grafana-kube-stack
      app.kubernetes.io/version: v25.11.14
      kustomize.component: prometheus-ingress
