apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - loki-virtualservice.yaml
  - loki-gateway.yaml

configMapGenerator:
  - name: loki-istio-params
    envs:
      - params.env
      
secretGenerator:
  - name: loki-tls
    namespace: istio-system
    behavior: create
    type: "kubernetes.io/tls"
    files:
      - tls.crt=loki.crt
      - tls.key=loki.key
      
generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      fieldPath: data.LOKI_DOMAINNAME
      kind: ConfigMap
      name: loki-istio-params
      version: v1
    targets:
      - select:
          name: loki-gateway
          kind: Gateway
        fieldPaths:
          - spec.servers.*.hosts.0
      - select:
          name: loki-vs
          kind: VirtualService
        fieldPaths:
          - spec.hosts.0
  - source:
      fieldPath: data.ingress_namespace
      kind: ConfigMap
      name: loki-istio-params
      version: v1
    targets:
      - select:
          name: loki-tls
          kind: Secret
        fieldPaths:
          - metadata.namespace

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: loki-ingress
      app.kubernetes.io/name: loki-ingress
      app.kubernetes.io/part-of: grafana-kube-stack
      app.kubernetes.io/version: v25.11.12
      kustomize.component: loki-ingress
