global:
  image:
    registry: null
    pullSecrets: []
  clusterDomain: "cluster.local"
  dnsService: "kube-dns"
  dnsNamespace: "kube-system"

loki:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 3.7.2
    pullPolicy: IfNotPresent
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: ${S3_REGION}
      bucketnames: loki-${GRAFANA_ENV}-chunk
      s3forcepathstyle: true
  compactor: {}
  pattern_ingester:
    enabled: true
  analytics:
    reporting_enabled: false
  querier:
      max_concurrent: 4
  ingester:
      chunk_encoding: snappy
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
  # enables multi-tenant (x-orgid)
  auth_enabled: true

  storage:
    type: s3
    bucketNames:
      chunks: loki-${GRAFANA_ENV}-chunk
      ruler: loki-${GRAFANA_ENV}-ruler
      admin: loki-${GRAFANA_ENV}-admin
    s3:
      # s3 URL can be used to specify the endpoint, access key, secret key, and bucket name this works well for S3 compatible storage or if you are hosting Loki on-premises and want to use S3 as the storage backend. Either use the s3 URL or the individual fields below (AWS endpoint, region, secret).
      #s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name
      # AWS endpoint URL
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      secretAccessKey: ${S3_SECRET_KEY}
      accessKeyId: ${S3_ACCESS_KEY}
      signatureVersion: v4
      s3ForcePathStyle: true
      insecure: false
      http_config: 
        insecure_skip_verify: ${S3_SKIP_VERIFY}

deploymentMode: Distributed

memcached:
  enabled: true
  image:
    repository: memcached
    tag: 1.6.41-alpine
memcachedExporter:
  enabled: true
  image:
    repository: prom/memcached-exporter
    tag: v0.16.0
  
minio:
  enabled: false

distributor:
  replicas: 3
  maxUnavailable: 2
  affinity: null
ingester:
  replicas: 3
  maxUnavailable: 1
  affinity: null
  zoneAwareReplication:
    enabled: false
querier:
  replicas: 3
  maxUnavailable: 1
  affinity: null
queryFrontend:
  replicas: 2
  maxUnavailable: 1
  affinity: null
queryScheduler:
  replicas: 2
  affinity: null
compactor:
  replicas: 1
  affinity: null
indexGateway:
  replicas: 1
  maxUnavailable: 1
  affinity: null

lokiCanary:
  enabled: false
  
gateway:
  enabled: true
  replicas: 1
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    tag: 1.31-alpine
  verboseLogging: false
  ingress:
    enabled: false
  basicAuth:
    enabled: true
    username: ${AGENT_USERNAME}
    password: ${AGENT_PASSWORD}
  affinity: null
    
test:
  enabled: false

# experimental
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0
ruler:
  enabled: false

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0

enterprise:
  enabled: false
  version: 3.6.8
  useExternalLicense: true
  externalLicenseName: null
  image:
    registry: docker.io
    repository: grafana/enterprise-logs
    tag: 3.6.8
  adminToken:
    secret: null
  provisioner:
    enabled: true
    image:
      registry: us-docker.pkg.dev
      repository: grafanalabs-global/docker-enterprise-provisioner-prod/enterprise-provisioner
      tag: latest
