---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources: []

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: false
    releaseName: prometheus
    namespace: monitoring
    version: 79.12.0
    repo: https://prometheus-community.github.io/helm-charts
    valuesFile: prom-values.yaml
    additionalValuesFiles:
      - prom-addScrapeConfigs.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: prometheus-community
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: grafana-kube-stack
      app.kubernetes.io/version: v26.01.20
      kustomize.component: prometheus
