global:
  imageRegistry: ""

crds:
  enabled: false

prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/worker: ""

kubeStateMetrics:
  enabled: false
  
kubernetesServiceMonitors:
  enabled: false
  
kubeApiServer:
  enabled: false

kubelet:
  enabled: false
  
kubeControllerManager:
  enabled: false
  
coreDns:
  enabled: false
kubeDns:
  enabled: false
  
kubeEtcd:
  enabled: false
  
kubeScheduler:
  enabled: false
  
kubeProxy:
  enabled: false
  
nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    enableFeatures:
      - metadata-wal-records
      - delayed-compaction
    remoteWrite:
      - url: http://mimir-distributor.monitoring.svc.cluster.local:8080/api/v1/push
        headers:
          X-Scope-OrgID: ${GRAFANA_ENV}
  service:
    sessionAffinity: ClientIP

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      node-role.kubernetes.io/worker: ""
  service:
    sessionAffinity: ClientIP

grafana:
  enabled: false
