global:
  imageRegistry: ""

crds:
  enabled: false

prometheusOperator:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    tag: v0.86.2
    pullPolicy: IfNotPresent
  admissionWebhooks:
    patch:
      image:
        registry: registry.k8s.io
        repository: ingress-nginx/kube-webhook-certgen
        tag: v1.6.5
  prometheusConfigReloader:
    image:
      registry: quay.io
      repository: prometheus-operator/prometheus-config-reloader
      tag: v0.86.2
  nodeSelector:
    node-role.kubernetes.io/worker: ""

kubeStateMetrics:
  enabled: false
  
kubernetesServiceMonitors:
  enabled: false
  
kubeApiServer:
  enabled: false

kubelet:
  enabled: false
  
kubeControllerManager:
  enabled: false
  
coreDns:
  enabled: false
kubeDns:
  enabled: false
  
kubeEtcd:
  enabled: false
  
kubeScheduler:
  enabled: false
  
kubeProxy:
  enabled: false
  
nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v3.8.0
      pullPolicy: IfNotPresent
    enableRemoteWriteReceiver: true
    enableFeatures:
      - metadata-wal-records
      - delayed-compaction
    remoteWrite:
      - url: http://mimir-distributor.monitoring.svc.cluster.local:8080/api/v1/push
        headers:
          X-Scope-OrgID: ${GRAFANA_ENV}
  service:
    sessionAffinity: ClientIP

alertmanager:
  alertmanagerSpec:
    image:
      registry: quay.io
      repository: prometheus/alertmanager
      tag: v0.29.0
      pullPolicy: IfNotPresent
    nodeSelector:
      node-role.kubernetes.io/worker: ""
  service:
    sessionAffinity: ClientIP

grafana:
  enabled: false
