---
- name: Install Alloy as Service Account
  hosts: all
  become: true
  vars:
    # System Install 
    alloy_user: 'alloy'
    alloy_group: 'alloy'
    alloy_shell: '/bin/false'
    alloy_home: '/var/lib/{{ alloy_user }}'
    alloy_groups:
      - systemd-journal
      - adm
    alloy_version: 'v1.14.0'
    alloy_config: 'config.alloy.j2'
    alloy_url: 'https://github.com/grafana/alloy/releases/download'
    alloy_archive: 'alloy-linux-amd64.zip'
    alloy_sha256: '7d12882f9c270804beeae3d519e995a1fcff18b7f50d6c5894438df0c799763a'
    # Alloy Config
    alloy_config_template: 'templates/config.alloy.j2'
    alloy_env_template: 'templates/alloy-env.j2'
    alloy_service_template: 'templates/alloy.service.j2'
    alloy_listen_ip: '127.0.0.1'
    alloy_listen_port: '12380'
    # Endpoints
    prometheus_endpoint: 'http://prometheus:9090'
    loki_endpoint: 'http://loki:3100'
    tempo_http_endpoint: 'tempo'
    tempo_otlp_endpoint: 'tempo:4317'
    tenant_org_id: 'fake'
    # Auth Secrets 
    agent_username: 'lgtmagent'
    agent_password: ''

  tasks:
    - name: Create primary group
      ansible.builtin.group:
        name: '{{ alloy_group }}'
        state: present

    - name: Create alloy user
      ansible.builtin.user:
        name: '{{ alloy_user }}'
        group: '{{ alloy_group }}'
        groups: "{{ alloy_groups | join(',') }}"
        append: true
        shell: '{{ alloy_shell }}'
        home: '{{ alloy_home }}'
        create_home: true
        state: present

    - name: Set home directory permissions 
      ansible.builtin.file:
        path: '{{ alloy_home }}'
        owner: '{{ alloy_user }}'
        group: '{{ alloy_group }}'
        mode: "0750"
        state: directory

    - name: Download the Alloy Archive
      ansible.builtin.get_url:
        url: '{{ alloy_url }}/{{ alloy_version }}/{{ alloy_archive }}'
        dest: '/tmp/{{ alloy_archive }}'
        checksum: 'sha256:{{ alloy_sha256 }}'
        mode: '0444'

    - name: Extract the Alloy Archive
      ansible.builtin.unarchive:
        src: '/tmp/{{ alloy_archive }}'
        dest: '/tmp'
        remote_src: true

    - name: Copy the Alloy Binary
      ansible.builtin.copy:
        src: '/tmp/alloy-linux-amd64'
        dest: '/usr/local/bin/alloy'
        owner: '{{ alloy_user }}'
        group: '{{ alloy_group }}'
        mode: '0755'
        remote_src: true

    - name: Remove Archive
      ansible.builtin.file:
        path: '/tmp/{{ alloy_archive }}'
        state: absent

    - name: Deploy the Alloy Configuration
      ansible.builtin.template:
        src: '{{ alloy_config_template }}'
        dest: '{{ alloy_home }}/config.alloy'
        owner: '{{ alloy_user }}'
        group: '{{ alloy_group }}'
        mode: '0640'

    - name: Deploy the default environment file
      ansible.builtin.template:
        src: '{{ alloy_env_template }}'
        dest: '/etc/default/alloy'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: Deploy the Systemd Service
      ansible.builtin.template:
        src: '{{ alloy_service_template }}'
        dest: '/etc/systemd/system/alloy.service'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: Enable the System Service
      ansible.builtin.systemd:
        name: 'alloy'
        daemon_reload: true
        enabled: true
        state: started
