apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - prometheus-virtualservice.yaml
  - prometheus-gateway.yaml
  - prometheus-envoyfilter.yaml

configMapGenerator:
  - name: prometheus-istio-params
    envs:
      - params.env

secretGenerator:
  - name: prometheus-tls
    namespace: istio-system
    behavior: create
    type: "kubernetes.io/tls"
    files:
      - tls.crt=prometheus.crt
      - tls.key=prometheus.key
  - name: prom-auth
    namespace: istio-system
    files:
      - auth

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      fieldPath: data.PROMETHEUS_DOMAINNAME
      kind: ConfigMap
      name: prometheus-istio-params
      version: v1
    targets:
      - select:
          name: prometheus-gateway
          kind: Gateway
        fieldPaths:
          - spec.servers.*.hosts.0
      - select:
          name: prometheus-vs
          kind: VirtualService
        fieldPaths:
          - spec.hosts.0
      - select:
          name: prom-auth-filter
          kind: EnvoyFilter
        fieldPaths:
          - spec.configPatches.*.match.routeConfiguration.vhost.name
  - source:
      fieldPath: data.ingress_namespace
      kind: ConfigMap
      name: prometheus-istio-params
      version: v1
    targets:
      - select:
          name: prometheus-tls
          kind: Secret
        fieldPaths:
          - metadata.namespace

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: prometheus-ingress
      app.kubernetes.io/name: istio-ingress
      app.kubernetes.io/part-of: grafana-kube-stack
      app.kubernetes.io/version: v25.11.13
      kustomize.component: prometheus-ingress
