---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources: 
  - ../dashboards/kubernetes
  - ../dashboards/trino 

secretGenerator:
  - name: grafana-admin
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true
  
helmCharts:
  - name: grafana
    includeCRDs: false
    releaseName: grafana
    namespace: monitoring
    version: 10.4.3
    repo: https://grafana.github.io/helm-charts
    valuesFile: grafana-values.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: grafana-kube-stack
      kustomize.component: grafana
