---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources: []

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: tempo-distributed
  includeCRDs: true
  releaseName: tempo
  namespace: monitoring
  version: 1.52.2
  repo: https://grafana.github.io/helm-charts
  valuesFile: tempo-values.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: tempo-distributed
      app.kubernetes.io/name: tempo
      app.kubernetes.io/part-of: grafana-kube-stack
      app.kubernetes.io/version: v26.01.05
      kustomize.component: tempo
