reportingEnabled: false

global:
  multitenancyEnabled: true
  image:
    registry: null
    pullSecrets: []

tempo:
  image:
   registry: docker.io
   repository: grafana/tempo
   pullSecrets: []
   pullPolicy: IfNotPresent
  
storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-${GRAFANA_ENV}-traces
      endpoint: ${S3_ENDPOINT}
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
      insecure: false
      tls_insecure_skip_verify: ${S3_SKIP_VERIFY}

minio:
  enabled: false

ingester:
  replicas: 1
  config:
    replication_factor: 1
  persistence:
    enabled: true
    inMemory: false
    size: 2Gi
    #storageClass: standard

metricsGenerator:
  enabled: false
  replicas: 1
  walEmptyDir:
    medium: "Memory"
    sizeLimit: 1Gi

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  jaeger:
    thriftHttp:
      enabled: true
  opencensus:
    enabled: false
  zipkin:
    enabled: false

distributor:
  replicas: 1
  config:
    log_received_spans:
      enabled: true

compactor:
  replicas: 1
  config:
    block_retention: 48h

memcached:
  enabled: true
  image:
    registry: null
    pullSecrets: []
    repository: memcached
    tag: 1.6.41-alpine
memcachedExporter:
  enabled: false
  image:
    registry: null
    pullSecrets: []
    repository: prom/memcached-exporter
    tag: v0.15.5

gateway:
  enabled: true
  image:
    registry: null
    repository: nginxinc/nginx-unprivileged
    tag: 1.29-alpine
  ingress:
    enabled: false
  basicAuth:
    enabled: true
    username: ${AGENT_USERNAME}
    password: ${AGENT_PASSWORD}
