alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
image:
  registry: "docker.io"
  repository: grafana/alloy
  tag: 1.4.0
  pullPolicy: IfNotPresent
  pullSecrets: []
