CREATE ROLE grafana_admin_role;
GRANT CONNECT ON DATABASE '${GRAFANA_DB_NAME}' TO grafana_admin_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA '${GRAFANA_DB_NAME}' TO grafana_admin_role;
GRANT USAGE,CREATE ON SCHEMA '${GRAFANA_DB_NAME}' TO grafana_admin_role;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA '${GRAFANA_DB_NAME}' TO grafana_admin_role;

CREATE USER '${GRAFANA_ADMIN_USER}' WITH ENCRYPTED PASSWORD '${GRAFANA_ADMIN_PASSWORD}';
GRANT grafana_admin_role TO ${GRAFANA_ADMIN_USER};
ALTER SCHEMA '${GRAFANA_DB_NAME}' OWNER TO grafana_admin_role;
