global:
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-credentials
  podAnnotations:
    bucketSecretVersion: "0"

image:
  repository: grafana/mimir
  tag: 3.0.4
  pullPolicy: IfNotPresent

alertmanager:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
  persistentVolume:
    size: 2Gi
    #storageClass: null

distributor:
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi

ingester:
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  persistentVolume:
    size: 2Gi
    #storageClass: null
  zoneAwareReplication:
    enabled: false

compactor:
  enabled: true
  replicas: 1
  persistentVolume:
    size: 2Gi
    #storageClass: null

querier:
  enabled: true
  replicas: 1
querier_scheduler:
  enabled: true
  replicas: 1
store_gateway:
  enabled: true
  replicas: 1
  persistentVolume:
    enabled: true
    size: 2Gi
    #storageClass: "-"
  zoneAwareReplication:
    enabled: false
  
memcached:
  image:
    repository: memcached
    tag: 1.6.41-alpine
    
memcachedExporter:
  enabled: true
  image:
    repository: prom/memcached-exporter
    tag: v0.15.5

chunks-cache:
  enabled: false
  replicas: 1
index-cache:
  enabled: false
  replicas: 1
metadata-cache:
  enabled: false
  replicas: 1
results-cache:
  enabled: false
  replicas: 1

kafka:
  enabled: true
  image:
    registry: docker.io
    repository: apache/kafka-native
    tag: 4.1.0
  persistence:
    enabled: true
    size: 1Gi  # default 5Gi
    storageClassName: ""
    
minio:
  enabled: false
ingress:
  enabled: false
nginx:
  enabled: false
  
metaMonitoring:
  serviceMonitor:
    enabled: false
  grafanaAgent:
    enabled: false
  metrics:
    enabled: false
    remote:
      url: ''
      headers: {}
      auth:
        username: ''
        passwordSecretName: ''
        passwordSecretKey: ''
    scrapeK8s:
      enabled: false

gateway:
  enabled: true
  replicas: 1
  ingress:
    enabled: false
  nginx:
    image:
      registry: docker.io
      repository: nginxinc/nginx-unprivileged
      tag: 1.29-alpine
    basicAuth:
      enabled: false
      username: ${AGENT_USERNAME}
      password: ${AGENT_PASSWORD}
      existingSecret: null

graphite:
  enabled: false
enterprise:
  enabled: false
  image:
    tag: r365-3fdf702d
