global:
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-credentials
  podAnnotations:
    bucketSecretVersion: "0"

image:
  repository: grafana/mimir
  tag: 2.17.0
  pullPolicy: IfNotPresent

alertmanager:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
  persistentVolume:
    size: 4Gi

distributor:
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi

ingester:
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  persistentVolume:
    size: 1Gi

compactor:
  persistentVolume:
    size: 1Gi
    
minio:
  enabled: false
nginx:
  enabled: false
store_gateway:
  enabled: false
  
metaMonitoring:
  serviceMonitor:
    enabled: false
  grafanaAgent:
    enabled: false
  metrics:
    enabled: false
    remote:
      url: ''
      headers: {}
      auth:
        username: ''
        passwordSecretName: ''
        passwordSecretKey: ''
    scrapeK8s:
      enabled: false

gateway:
  enabled: false
  enabledNonEnterprise: false
  image:
    repository: grafana/mimir-enterprise
    tag: 2.17.0
  replicas: 1
  ingress:
    enabled: false
  nginx:
    image:
      registry: docker.io
      repository: nginxinc/nginx-unprivileged
      tag: 1.29-alpine
    basicAuth:
      enabled: false
      username: null
      password: null
      existingSecret: null

graphite:
  enabled: false
enterprise:
  enabled: false
