---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - tempo-gateway.yaml
  - tempo-vs-https.yaml
  - tempo-vs-grpc.yaml

configMapGenerator:
  - name: tempo-istio-params
    envs:
      - params.env

secretGenerator:
  - name: tempo-tls
    behavior: create
    type: "kubernetes.io/tls"
    files:
      - tls.crt=tempo.crt
      - tls.key=tempo.key

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      fieldPath: data.TEMPO_DOMAINNAME
      kind: ConfigMap
      name: tempo-istio-params
      version: v1
    targets:
      - select:
          name: tempo-gateway
          kind: Gateway
        fieldPaths:
          - spec.servers.*.hosts.0
      - select:
          name: tempo-vs-https
          kind: VirtualService
        fieldPaths:
          - spec.hosts.0
      - select:
          name: tempo-vs-grpc
          kind: VirtualService
        fieldPaths:
          - spec.hosts.0
  - source:
      fieldPath: data.ingress_namespace
      kind: ConfigMap
      name: tempo-istio-params
      version: v1
    targets:
      - select:
          name: tempo-tls
          kind: Secret
        fieldPaths:
          - metadata.namespace

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: tempo-istio-ingress
      app.kubernetes.io/name: tempo-ingress
      app.kubernetes.io/part-of: grafana-kube-stack
      app.kubernetes.io/version: v26.01.15
      kustomize.component: tempo-ingress
