---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ../../base
 
secretGenerator:
  - name: tempo-license
    files:
      - license.jwt=license.jwt

generatorOptions:
  disableNameSuffixHash: true

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tempo-gateway
        namespace: $(namespace)
      spec:
        template:
          spec:
            containers:
              - name: nginx
                image: docker.io/nginxinc/nginx-unprivileged:1.29-alpine
