replicas: 1

deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

image:
  registry: docker.io
  repository: grafana/mcp-grafana
  tag: 0.8.2

grafana:
  url: http://grafana.monitoring.svc.cluster.local:3000
  apiKeySecret:
    name: "mcp-grafana-apikey"
    key: "apikey"

debug: false

service:
  enabled: true
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
