---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources: []

secretGenerator:
  - name: mcp-grafana-apikey
    envs:
      - secrets.env


helmCharts:
  - name: grafana-mcp
    includeCRDs: false
    releaseName: grafana-mcp
    namespace: monitoring
    version: 0.3.1
    repo: https://grafana-community.github.io/helm-charts
    valuesFile: grafana-mcp-values.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: grafana-kube-stack
      kustomize.component: grafana-mcp
