---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - tempo-ingress.yaml

configMapGenerator:
  - name: tempo-nginx-params
    envs:
      - params.env

secretGenerator:
  - name: tempo-tls
    behavior: create
    type: "kubernetes.io/tls"
    files:
      - tls.crt=tempo.crt
      - tls.key=tempo.key

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      fieldPath: data.TEMPO_DOMAINNAME
      kind: ConfigMap
      name: tempo-nginx-params
      version: v1
    targets:
      - select:
          name: tempo-ingress
          kind: Ingress
        fieldPaths:
          - spec.tls.*.hosts.0
          - spec.rules.0.host
  - source:
      fieldPath: data.namespace
      kind: ConfigMap
      name: tempo-nginx-params
      version: v1
    targets:
      - select:
          name: tempo-ingress
          kind: ingress
        fieldPaths:
          - metadata.namespace

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: tempo-ingress
      app.kubernetes.io/name: tempo-ingress
      app.kubernetes.io/part-of: grafana-kube-stack
      app.kubernetes.io/version: v25.11.13
      kustomize.component: tempo-ingress
