name: 'Kustomize Build Action'

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'develop' ]
  pull_request:
    branches: [ 'master', 'main' ]

env:
  GRAFANA_ENV: test
  S3_ENDPOINT: s3a://minio-svc
  S3_REGION: us-southwest-3
  S3_ACCESS_KEY: test
  S3_SECRET_KEY: test
  S3_SKIP_VERIFY: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Grafana
        run: ./bin/grafana-stack-setup.sh example

      - name: Build Mimir
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './mimir'

      - name: Build Prometheus
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './prometheus'

      - name: Build Loki
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './loki'

      - name: Build Tempo
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './tempo'

      - name: Build Grafana
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './grafana'